spring.datasource.url=jdbc:postgresql://localhost:5432/tool_db
spring.datasource.username=uday
spring.datasource.password=Uday@3404

spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true
spring.jpa.show-sql=true